export default {
    default:  {
        axisYWidth: 50,
        barBackgroundColor: "#8e929a",
        barEndcolor: "#2563f9",
        barStartColor: "#57eabf",
        barSymbolImage: undefined,
        barSymbolMargin: 3,
        barSymbolSizeX: 18,
        barSymbolSizeY: 18,
        barSymbolType: "default",
        barWidth: 18,
        categoryLen: 5,
        clickLeftMouse: "none",
        displayPolicy: "none",
        firstBarPositionX: 1,
        firstBarPositionY: -13,
        labelTextStyle: {
            fontFamily: '微软雅黑',
            fontSize: '1.0X',
            fontWeight: 'Normal',
            fontStyle: 'Normal',
            color: '#f0f0f0'
        },
        radiusLeftDown: 10,
        radiusLeftTop: 10,
        radiusRightDown: 10,
        radiusRightTop: 10,
        rankingBackgroundColor: "#444a58",
        rankingBackgroundImage: undefined,
        rankingConditionCollection: [{
            rankingConditionValue: "1",
            rankingReplaceValue: '',
            rankingFontColor: '',
            rankingConditionColor: '#509dea',
            rankingConditionImage:'',
            rankingStartConditionColor: "#509dea",
            rankingEndConditionColor: "#d3e7fa"
        },{
            rankingConditionValue: "2",
            rankingReplaceValue: '',
            rankingFontColor: '',
            rankingConditionColor: '#08bc9b',
            rankingConditionImage:'',
            rankingStartConditionColor: "#08bc9b",
            rankingEndConditionColor: "#c1eee6"
        },{
            rankingConditionValue: "3",
            rankingReplaceValue: '',
            rankingFontColor: '',
            rankingConditionColor: '#8c7df2',
            rankingConditionImage:'',
            rankingStartConditionColor: "#8c7df2",
            rankingEndConditionColor: "#e2dffc"
        }],
        rankingShape: "circular",
        rankingSize: 8,
        rankingTextStyle: {
            fontFamily: '微软雅黑',
            fontSize: '1.0X',
            fontWeight: 'Normal',
            fontStyle: 'Normal',
            color: '#f0f0f0'
        },
        rotationDegree: 0,
        secondBarPositionX: -50,
        secondBarPositionY: 0,
        showBackgroundColor: false,
        showBarLabel: true,
        showFirstBarActual: false,
        showFirstBarActualUnit: "auto",
        showFirstBarCategory: true,
        showFirstBarContrast: false,
        showFirstBarContrastUnit: "auto",
        showFirstBarPercent: false,
        showFirstPercentFormate: 2,
        showLabel: true,
        showRanking: true,
        showSecondBarActual: false,
        showSecondBarActualUnit: "auto",
        showSecondBarContrast: false,
        showSecondBarContrastUnit: "auto",
        showSecondBarPercent: true,
        showSecondPercentFormate: 2,
        sortAccording: "accordingPercent",
        sorttype: "desc",
        textStyle: {
            fontFamily: '微软雅黑',
            fontSize: '1.0X',
            fontWeight: 'Normal',
            fontStyle: 'Normal',
            color: '#f0f0f0'
        }
    },
    style1: {
        showSecondBarActual: true,
        showSecondBarPercent: false,
        showBackgroundColor: true,
        rankingSizeX: 10,
        rankingSizeY: 10,
        rankingConditionCollection: [{
            rankingConditionValue: "1",
            rankingReplaceValue: '',
            rankingFontColor: '',
            rankingConditionColor: '#509dea',
            rankingConditionImage:'',
            rankingStartConditionColor: "#509dea",
            rankingEndConditionColor: "#d3e7fa"
        },{
            rankingConditionValue: "2",
            rankingReplaceValue: '',
            rankingFontColor: '',
            rankingConditionColor: '#08bc9b',
            rankingConditionImage:'',
            rankingStartConditionColor: "#08bc9b",
            rankingEndConditionColor: "#c1eee6"
        },{
            rankingConditionValue: "3",
            rankingReplaceValue: '',
            rankingFontColor: '',
            rankingConditionColor: '#8c7df2',
            rankingConditionImage:'',
            rankingStartConditionColor: "#8c7df2",
            rankingEndConditionColor: "#e2dffc"
        }]
    },
    style2: {
        showSecondBarActual: true,
        showSecondBarPercent: false,
        barStartColor: '#f5ba1a',
        barEndcolor: '#bc7df2',
        barSymbolSizeY: 5,
        barSymbolType: 'rect',
        rankingShape: 'square',
        rankingSize: 8,
        showBackgroundColor: true,
        secondBarPositionX: -40,
        secondBarPositionY: -10,
        rankingSizeX: 10,
        rankingSizeY: 10,
        rankingConditionCollection: [{
            rankingConditionValue: "1",
            rankingReplaceValue: '冠',
            rankingFontColor: '',
            rankingConditionColor: '#509eea',
            rankingConditionImage:'',
            rankingStartConditionColor: "#509dea",
            rankingEndConditionColor: "#d3e7fa"
        },{
            rankingConditionValue: "2",
            rankingReplaceValue: '亚',
            rankingFontColor: '',
            rankingConditionColor: '#08bc9b',
            rankingConditionImage:'',
            rankingStartConditionColor: "#08bc9b",
            rankingEndConditionColor: "#c1eee6"
        },{
            rankingConditionValue: "3",
            rankingReplaceValue: '季',
            rankingFontColor: '',
            rankingConditionColor: '#8c7df2',
            rankingConditionImage:'',
            rankingStartConditionColor: "#8c7df2",
            rankingEndConditionColor: "#e2dffc"
        }]
    },
    style3: {
        showSecondBarActual: true,
        showSecondBarPercent: false,
        barSymbolType: 'circle',
        barSymbolSizeX: 12,
        barSymbolSizeY: 12,
        rankingShape: 'square',
        rankingSize: 6,
        axisYWidth: 5,
        firstBarPositionX:25,
        firstBarPositionY: -18,
        secondBarPositionX: 0,
        secondBarPositionY: -22,
        showBackgroundColor: true,
        rankingSizeX: 10,
        rankingSizeY: 10,
        rankingConditionCollection: [{
            rankingConditionValue: "1",
            rankingReplaceValue: '',
            rankingFontColor: '',
            rankingConditionColor: '#f5ba1a',
            rankingConditionImage:'',
            rankingStartConditionColor: "#509dea",
            rankingEndConditionColor: "#d3e7fa"
        },{
            rankingConditionValue: "2",
            rankingReplaceValue: '',
            rankingFontColor: '',
            rankingConditionColor: '#08bc9b',
            rankingConditionImage:'',
            rankingStartConditionColor: "#08bc9b",
            rankingEndConditionColor: "#c1eee6"
        },{
            rankingConditionValue: "3",
            rankingReplaceValue: '',
            rankingFontColor: '',
            rankingConditionColor: '#8c7df2',
            rankingConditionImage:'',
            rankingStartConditionColor: "#8c7df2",
            rankingEndConditionColor: "#e2dffc"
        }],
    },
    style4:  {
        axisYWidth: 50,
        barBackgroundColor: "#444a58",
        barEndcolor: "#2563f9",
        barStartColor: "#57eabf",
        barSymbolImage: undefined,
        barSymbolMargin: 3,
        barSymbolSizeX: 18,
        barSymbolSizeY: 18,
        barSymbolType: "default",//pictorialBar
        barWidth: 18,
        categoryLen: 5,
        clickLeftMouse: "none",
        displayPolicy: "none",
        firstBarPositionX: 1,
        firstBarPositionY: -13,
        rankingSizeX: 10,
        rankingSizeY: 10,
        labelTextStyle: {
            fontFamily: '微软雅黑',
            fontSize: '1.0X',
            fontWeight: 'Normal',
            fontStyle: 'Normal',
            color: '#f0f0f0'
        },
        radiusLeftDown: 10,
        radiusLeftTop: 10,
        radiusRightDown: 10,
        radiusRightTop: 10,
        rankingBackgroundColor: "#444a58",
        rankingBackgroundImage: undefined,
        rankingConditionCollection: [{
            rankingConditionValue: "1",
            rankingReplaceValue: '',
            rankingFontColor: '',
            rankingConditionColor: '#509dea',
            rankingConditionImage:'',
            rankingStartConditionColor: "#509dea",
            rankingEndConditionColor: "#d3e7fa"
           },{
            rankingConditionValue: "2",
            rankingReplaceValue: '',
            rankingFontColor: '',
            rankingConditionColor: '#08bc9b',
            rankingConditionImage:'',
            rankingStartConditionColor: "#08bc9b",
            rankingEndConditionColor: "#c1eee6"
        },{
            rankingConditionValue: "3",
            rankingReplaceValue: '',
            rankingFontColor: '',
            rankingConditionColor: '#8c7df2',
            rankingConditionImage:'',
            rankingStartConditionColor: "#8c7df2",
            rankingEndConditionColor: "#e2dffc"
        }],
        rankingShape: "square",
        rankingSize: 8,
        rankingTextStyle: {
            fontFamily: '微软雅黑',
            fontSize: '1.0X',
            fontWeight: 'Normal',
            fontStyle: 'Normal',
            color: '#f0f0f0'
        },
        rotationDegree: 0,
        secondBarPositionX: -42,
        secondBarPositionY: -10,
        showBackgroundColor: true,
        showBarLabel: true,
        showFirstBarActual: false,
        showFirstBarActualUnit: "auto",
        showFirstBarCategory: true,
        showFirstBarContrast: false,
        showFirstBarContrastUnit: "auto",
        showFirstBarPercent: false,
        showFirstPercentFormate: 2,
        showLabel: true,
        showRanking: true,
        showSecondBarActual: false,
        showSecondBarActualUnit: "auto",
        showSecondBarContrast: false,
        showSecondBarContrastUnit: "auto",
        showSecondBarPercent: true,
        showSecondPercentFormate: 2,
        sortAccording: "accordingPercent",
        sorttype: "desc",
        textStyle: {
            fontFamily: '微软雅黑',
            fontSize: '1.0X',
            fontWeight: 'Normal',
            fontStyle: 'Normal',
            color: '#f0f0f0'
        }
     }
}