export default {
    default:  {
        Actual: "dataset",
        Contrast: "dataset",
        DetailDisplayUnit: "",
        DetailDisplayUnitTextStyle: {
            fontFamily: '微软雅黑',
            fontSize: '10pt',
            fontWeight: 'Normal',
            fontStyle: 'Normal',
            color: '#f0f0f0'
        },
        axisLabelColor: "#f0f0f0",
        axisLabelCustom: [],
        axisLabelShadowDistance: 2,
        axisLabelTextStyle: {fontSize: '1.0X'},
        axisTickColor: "#000",
        axisTickNum: 10,
        axisTickShadowDistance: 0,
        axisTickWidth: 1,
        customActual: "50",
        customContrast: "100",
        dataLabel1LineHeight: 30,
        dataLabel1TextStyle: {fontFamily: '微软雅黑', fontSize: '20pt', fontWeight: 'Normal', fontStyle: 'Normal', color: '#f0f0f0'},
        dataLabel1XPosition: 0,
        dataLabel1YPosition: 0,
        dataLabel2LineHeight: 30,
        dataLabel2TextStyle: {fontFamily: '微软雅黑', fontSize: '12pt', fontWeight: 'Normal', fontStyle: 'Normal', color: '#f0f0f0'},
        dataLabel2XPosition: 0,
        dataLabel2YPosition: 20,
        dialColorUseToDial: false,
        dialColorUseToLabel1: false,
        dialColorUseToLabel2: false,
        dialColorUseToPointer: false,
        dialColorUseToShadow: false,
        dialSectionColor: [],
        endAngle: -270,
        gaugeBgColor: "#8c7df2",
        gaugeCircle: true,
        gaugeCircleColor: "#fff",
        gaugeCircleR: 50,
        gaugeCircleWidth: 2,
        gaugeGear: true,
        gaugeR: 100,
        gaugeWidth: 50,
        gaugeXPosition: 50,
        gaugeYPosition: 50,
        gearColor: "#509dea",
        gearLength: 30,
        gearNumber: 50,
        gearWidth: 5,
        progressRoundCap: false,
        progressRoundCapWidth: 50,
        progressRoundColor: "#509dea",
        scope: false,
        showBgImage: false,
        showActual1: false,
        showActual2: true,
        showAxisLabel: true,
        showContrast1: false,
        showContrast2: true,
        showDataLabel1: true,
        showDataLabel2: true,
        showDefaultLabel: true,
        showDetail1: true,
        showDetail2: false,
        showProgress: true,
        showSubTitle: true,
        showaxisTick: true,
        showsplitLine: true,
        splitLineColor: "#000",
        splitLineDistance: -10,
        splitLineWidth: 10,
        startAngle: 90,

        subtitle: "",
        textStyle: {fontFamily: '微软雅黑', fontSize: '15pt', fontWeight: 'Normal', fontStyle: 'Normal', color: '#f0f0f0'},
        titleXPosition: 0,
        titleYPosition: -20,
    },
    style1: {
        gaugeGear: false,
        gaugeCircle: false,
        progressRoundCap: true,
        showsplitLine: false
    },
    style2: {
        gaugeGear: false,
        gaugeCircle: false,
        progressRoundCap: true,
        showsplitLine: false,
        gaugeWidth: 30
    },
    style3: {
       
    },
    style4: {
        
    },
}