export default {
    default:  {
        Actual: "dataset",
        Contrast: "dataset",
        DetailDisplayUnit: "",
        DetailDisplayUnitTextStyle: {fontFamily: '微软雅黑', fontSize: '1.0x', fontWeight: 'Normal', fontStyle: 'Normal', color: '#f0f0f0'},
        bgAnimateDirection: "Positive",
        bgAnimateTime: 10,
        bgImage: "",
        bgImageAnimate: true,
        bgImageSize: 100,
        customActual: "50",
        customContrast: "100",
        dataLabel1LineHeight: 30,
        dataLabel1TextStyle: {fontFamily: '微软雅黑', fontSize: '3.0X', fontWeight: 'Normal', fontStyle: 'Normal', color: '#f0f0f0'},
        dataLabel1XPosition: 0,
        dataLabel1YPosition: 0,
        dataLabel2LineHeight: 30,
        dataLabel2TextStyle: {fontFamily: '微软雅黑', fontSize: '1.2X', fontWeight: 'Normal', fontStyle: 'Normal', color: '#f0f0f0'},
        dataLabel2XPosition: 0,
        dataLabel2YPosition: 20,
        dialColorUseToCircle: false,
        dialColorUseToLabel1: false,
        dialColorUseToLabel2: false,
        dialColorUseToProgress: false,
        dialSectionColor: [{
            "section": 1,
            "sectionMax": 25,
            "color": "#f84d4d"
        },
        {
            "section": 2,
            "sectionMax": 50,
            "color": "#f5ba1a"
        },{
            "section": 3,
            "sectionMax": 75,
            "color": "#509dea"
        },{
            "section": 4,
            "sectionMax": 100,
            "color": "#08bc9b"
        }],
        endAngle: -270,
        gaugeBgColor: "#8c7df2",
        gaugeCircle: true,
        gaugeCircleDge: true,
        gaugeCircleEndColor: "#000",
        gaugeCircleInsideR: 0,
        gaugeCircleOutsideR: 50,
        gaugeCircleStartColor: "#8c7df2",
        gaugeGear: true,
        gaugeR: 100,
        gaugeWidth: 25,
        gaugeXPosition: 50,
        gaugeYPosition: 50,
        gearColor: "#509dea",
        gearLength: 30,
        gearNumber: 50,
        gearR: 100,
        gearShadowColor: "#fff",
        gearWidth: 5,
        initStyleName: "default",
        progressOffset: 0,
        progressRoundCap: false,
        progressRoundCapWidth: 25,
        progressRoundColor: "#509dea",
        progressRoundColorTest: "#fff",
        showActual1: false,
        showActual2: true,
        showBgImage: false,
        showContrast1: false,
        showContrast2: true,
        showDataLabel1: true,
        showDataLabel2: true,
        showDetail1: true,
        showDetail2: false,
        showProgress: true,
        showSubTitle: true,
        showsplitLine: true,
        splitLineColor: "#000",
        splitLineDistance: -10,
        splitLineNumber: 15,
        splitLineWidth: 10,
        startAngle: 90,
        styleName: "default",
        subtitle: "",
        textStyle: {fontFamily: '微软雅黑', fontSize: '1.5X', fontWeight: 'Normal', fontStyle: 'Normal', color: '#f0f0f0'},
        titleXPosition: 0,
        titleYPosition: -20,
    },
    style1: {
        gaugeBgColor: "rgba(80,157,234,0.7)",
        gaugeCircleStartColor: "#08c7df",
        gaugeGear: false,
        gaugeR: 120,
        gaugeWidth: 20,
        progressRoundCapWidth: 20,
        progressRoundColor: "#08bc9b",
        progressRoundColorTest: "#08bc9b",
    },
    style2: {
        gaugeBgColor: "rgba(180,180,180,0.8)",
        gaugeCircleOutsideR: 45,
        gaugeCircleStartColor: "#08bc9b",
        gaugeGear: false,
        gaugeR: 120,
        gaugeWidth: 25,
        gearLength: 25,
        progressRoundCap: true,
        progressRoundCapWidth: 25,
        progressRoundColor: "#08bc9b",
        progressRoundColorTest: "#08bc9b",
        showsplitLine: false,
        titleYPosition: -25,
    },
    style3: {
        dataLabel1TextStyle: {fontFamily: '微软雅黑', fontSize: '5.0X', fontWeight: 'Normal', fontStyle: 'Normal', color: '#f0f0f0'},
        endAngle: -45,
        gaugeBgColor: "rgb(49,213,48)",
        gaugeCircle: false,
        gaugeGear: false,
        gaugeR: 130,
        gaugeWidth: 7,
        progressRoundCapWidth: 25,
        progressRoundColor: "rgba(41, 182, 41, 0.6)",
        progressRoundColorTest: "rgba(41, 182, 41, 0.6)",
        showsplitLine: false,
        startAngle: 225,
        titleYPosition: 45,
    },
    style4: {
        bgImageSize: 95,
        gaugeBgColor: "rgba(80,157,234,0.7)",
        gaugeCircleStartColor: "#08c7df",
        gaugeGear: false,
        gaugeR: 120,
        gaugeWidth: 20,
        progressRoundCapWidth: 20,
        progressRoundColor: "#08bc9b",
        progressRoundColorTest: "#08bc9b",
        showBgImage: true,
        bgImageSet: 'bgImage1'
    },
    style5: {
        endAngle: -45,
        gaugeBgColor: "rgba(80,157,234,0.7)",
        gaugeCircleDge: false,
        gaugeCircleStartColor: "#08c7df",
        gaugeR: 110,
        gaugeWidth: 20,
        gearColor: "rgba(22, 84, 255, 0.5)",
        gearLength: 15,
        gearNumber: 35,
        gearR: 102,
        gearShadowColor: "rgba(240,240,240,0.5)",
        gearWidth: 3,
        progressRoundCapWidth: 20,
        progressRoundColor: "#08bc9b",
        progressRoundColorTest: "#08bc9b",
        startAngle: 225,
    },
    style6: {
        showBgImage: true,
        gaugeBgColor: "rgba(80,157,234,0.7)",
        gaugeCircle: false,
        gaugeR: 105,
        gaugeWidth: 20,
        gearColor: "rgba(22, 84, 255, 0.5)",
        gearLength: 15,
        gearNumber: 60,
        gearR: 102,
        gearShadowColor: "rgba(240,240,240,0.5)",
        gearWidth: 3,
        progressRoundCapWidth: 20,
        progressRoundColor: "rgb(49,213,48)",
        progressRoundColorTest: "rgb(49,213,48)",
        bgImageSet: 'bgImage2'
    },
    style7: {
        dataLabel1TextStyle: {fontFamily: '微软雅黑', fontSize: '5.0X', fontWeight: 'Normal', fontStyle: 'Normal', color: '#f0f0f0'},
        gaugeBgColor: "#313443",
        gaugeCircleInsideR: 48,
        gaugeCircleStartColor: "rgba(41, 182, 41, 0.7)",
        gaugeGear: false,
        gaugeR: 120,
        gaugeWidth: 27,
        progressRoundCapWidth: 20,
        progressRoundColor: "rgba(41, 182, 41, 0.7)",
        progressRoundColorTest: "#29b629",
        showDataLabel2: false,
        titleYPosition: 25,
    },
    style8: {
        dataLabel1TextStyle: {fontFamily: '微软雅黑', fontSize: '5.0X', fontWeight: 'Normal', fontStyle: 'Normal', color: '#f0f0f0'},
        dataLabel1YPosition: -25,
        dialColorUseToLabel1: true,
        dialColorUseToProgress: true,
        endAngle: 0,
        gaugeBgColor: "rgba(80,157,234,0.6)",
        gaugeCircle: false,
        gaugeGear: false,
        gaugeR: 170,
        gaugeWidth: 25,
        gaugeYPosition: 85,
        progressRoundCapWidth: 25,
        progressRoundColor: "#08bc9b",
        progressRoundColorTest: "#08bc9b",
        showDataLabel2: false,
        startAngle: 180,
        titleYPosition: -2,
    },
    style9: {
        dataLabel1TextStyle: {fontFamily: '微软雅黑', fontSize: '5.0X', fontWeight: 'Normal', fontStyle: 'Normal', color: '#f0f0f0'},
        dataLabel1YPosition: -25,
        dialColorUseToLabel1: true,
        dialColorUseToProgress: true,
        endAngle: 0,
        gaugeBgColor: "rgba(80,157,234,0.6)",
        gaugeCircle: false,
        gaugeGear: false,
        gaugeR: 170,
        gaugeWidth: 25,
        gaugeYPosition: 85,
        progressRoundCap: true,
        progressRoundCapWidth: 25,
        progressRoundColorTest: "#509dea",
        showDataLabel2: false,
        showsplitLine: false,
        startAngle: 180,
        titleYPosition: -2,
    },
}